# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment - NeoForge 1.21.1
# https://projects.neoforged.net/neoforged/neoforge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.204
loader_version_range=[1,)

# Mod
mod_id=hats
mod_name=Hats
mod_license=All Rights Reserved
mod_version=1.21.1-1.3.0
mod_group_id=com.astryxion.hats
mod_authors=Astryxion
mod_description=Embark on a hunt to collect unique, high-quality hats! Features a dedicated custom hat slot and a unique progression system.
archive_base_name=hatsneoforge
