# Sets default memory used for gradle commands.
# Increased to 4G for smoother building/decompilation of the release artifact.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

## Mod Properties
# Must match com.astryxion.hats.Hats.MODID
mod_id=hats
mod_name=Hats
mod_license=All Rights Reserved
mod_version=2.3.0
mod_group_id=com.astryxion.hats
mod_authors=Astryxion
mod_description=Embark on a hunt to collect unique, high-quality hats! Features a dedicated custom hat slot and a unique progression system.