# Sets default memory used for gradle commands. Can be overridden with command line or user gradle.properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment - NeoForge 26.1
# https://projects.neoforged.net/neoforged/neoforge
minecraft_version=26.1
minecraft_version_range=[26.1,]
neo_version=26.1.0.19-beta
loader_version_range=[1,)

# Mod
mod_id=hats
mod_name=Hats
mod_license=All Rights Reserved
mod_version=26.1-1.0.0
mod_group_id=com.astryxion.hats
mod_authors=Astryxion
mod_description=Embark on a hunt to collect unique, high-quality hats! Features a dedicated custom hat slot and a unique progression system.
archive_base_name=hatsneoforge
